--------------------------------------- RESUMEN DE TRANSFERENCIAS INMEDIATAS -------------------------------------------------------------------------------
SELECT MON_TRANSFERENCIA,MON_COMISION,COD_CANAL,TIP_TRANSFERENCIA,IND_ESTADO_OPERACION,* 
FROM [CC].[CC_TIN_INMEDIATA_TRANSACCION_ORDEN_TRANSFERENCIA]
WHERE FEC_REGISTRO > GETDATE()-35;

SELECT * FROM CC.CC_BITACORAS_TRANSFERENCIAS_INMEDIATAS WHERE IND_BITACORA = 'R';

-------------------------------------- RESUMEN DE TRANSFERENCIAS DIFERIDAS -------------------------------------------------------------------------------
EXEC CC.USP_CC_RPT_TRANSFERENCIAS_PRESENTADAS_SALIDA_CCE 'D','20250401','20250430', '%'
EXEC CC.USP_CC_RPT_TRANSFERENCIAS_RECIBIDAS_ENTRADA_CCE 'D','20250401','20250430','%','%'

SELECT * FROM BA.BA_TIN_CABECERA_ARCHIVO;
SELECT * FROM BA.BA_TIN_CABECERA_LOTE;
SELECT * FROM BA.BA_TIN_DETALLE_ARCHIVO_RESPUESTA WHERE DET_REGISTRO LIKE '%HORA%' OR DET_REGISTRO LIKE '%FECHA%';
SELECT * FROM BA.BA_TIN_REGISTRO_ADICIONAL;
SELECT * FROM BA.BA_TIN_REGISTRO_ADICIONAL_DEVOLUCION;
SELECT * FROM BA.BA_TIN_REGISTRO_INDIVIDUAL;
SELECT * FROM BA.BA_TIN_TERMINO_ARCHIVO;
SELECT * FROM BA.BA_TIN_TERMINO_LOTE;
SELECT * FROM BA.BA_TIN_ARCHIVO_CONFIRMACION_REGISTRO_TIPO_0;
SELECT * FROM BA.BA_TIN_ARCHIVO_CONFIRMACION_REGISTRO_TIPO_1;
SELECT * FROM BA.BA_TIN_ARCHIVO_CONFIRMACION_REGISTRO_TIPO_2;
SELECT * FROM BA.BA_TIN_ARCHIVO_CONFIRMACION_REGISTRO_TIPO_3;
SELECT * FROM BA.BA_TIN_ARCHIVO_CONFIRMACION_REGISTRO_TIPO_4;
SELECT * FROM BA.BA_TIN_ARCHIVO_CONFIRMACION_REGISTRO_TIPO_L;

------------------------------------------------------ TABLAS ADICIONALES -----------------------------------------------------------------------------------

SELECT * FROM CC.CC_MOVIMTO_DIARIO WHERE NUM_MOVIMIENTO = '46351953';
SELECT * FROM CC.CC_MOVIMTO_DIARIO WHERE NUM_MOV_FUENTE = '46351953';
SELECT * FROM CC.CC_MOVIMTO_MENSUAL WHERE NUM_MOVIMIENTO = '46351953';
SELECT * FROM CC.CC_MOVIMTO_MENSUAL WHERE NUM_MOV_FUENTE = '46351953';
SELECT * FROM CC.CC_MOVIMTO_HISTORICO WHERE NUM_MOVIMIENTO = '46351239';

SELECT * FROM CC.CC_TRANSFERENCIAS_ENCABEZADO WHERE NUM_TRANSFERENCIA = '62566';
SELECT * FROM CC.CC_TRANSFERENCIAS_DETALLE_CCE WHERE NUM_TRANSFERENCIA = '62566';
SELECT * FROM CC.CC_TRANSFERENCIAS_DETALLE_ENTRANTES_CCE WHERE NUM_TRANSFERENCIA = '62566';

SELECT * FROM CG.CG_ASTO_RESUMEN WHERE NUM_ASIENTO = '31983248';
SELECT * FROM CG.CG_ASTO_DETALLE WHERE NUM_ASIENTO = '31983248';

SELECT * FROM CJ.CJ_MENOR_CUANTIA_ENCA WHERE NUM_OPERACION = '13844140';
SELECT * FROM CJ.CJ_MENOR_CUANTIA_DETA WHERE NUM_OPERACION = '13844140';
SELECT * FROM CJ.CJ_MENOR_CUANTIA_INTERVI WHERE NUM_OPERACION = '13844140';

SELECT * FROM CJ.CJ_OPERACION_UNICA_LAVADO WHERE NUM_MOVIMIENTO = '397532';
SELECT * FROM CJ.CJ_OPERACION_UNICA_DETALLE WHERE NUM_MOVIMIENTO_LAV = '397533';

SELECT * FROM BA.BA_TRAN_DIARIO WHERE NUM_SECUENCIA = '157104';

----------------------------------------------------------------------- SCRIPT PARA MI TESIS TIN INMEDIATA --------------------------------------------------------------
DECLARE @GD_FEC_INICIO DATE = '20250901';
DECLARE @GD_FEC_FIN    DATE = '20251231';

SELECT
    A.ID_TRANSACCION,
    CASE WHEN A.IND_TRANSACCION = 'O' THEN 'SALIENTE' ELSE 'ENTRANTE' END AS IND_TRANSACCION,
    A.NUM_TRANSFERENCIA,
    CASE 
        WHEN A.TIP_TRANSFERENCIA = '320' THEN 'TRANSFERENCIA ORDINARIA' 
        ELSE 'PAGO TARJETA DE CREDITO' 
    END AS TIP_TRANSFERENCIA,
    B.DES_TIPO_ID AS TIP_DOC_ORIGINANTE,
    A.NUM_IDENTIDAD_ORIGINANTE,
    A.NOM_ORIGINANTE,
    C.DES_CANAL,
    CASE WHEN A.COD_MONEDA = '1' THEN 'SOLES' ELSE 'DOLARES' END AS DES_MONEDA,
    A.MON_TRANSFERENCIA,
    TD.MON_COMISION AS MON_COMISION_CMACT,
    A.MON_COMISION AS MON_COMISION_CCE,
    MON_COMISION_TOTAL = ISNULL(TD.MON_COMISION,0) - ISNULL(A.MON_COMISION,0),
    CASE
        WHEN 
            DATEPART(WEEKDAY, CAST(A.FEC_REGISTRO AS DATE)) NOT IN (6, 7)
            AND NOT EXISTS (
                SELECT 1
                FROM CF.CF_TIN_DIA_NO_LABORABLE DNL WITH (NOLOCK)
                WHERE DNL.IND_ESTADO = 'A'
                  AND DNL.FEC_NO_LABORABLE = CAST(A.FEC_REGISTRO AS DATE)
            )
            AND NOT EXISTS (
                SELECT 1
                FROM CF.CF_FERIADO_NACIONAL FN WITH (NOLOCK)
                WHERE FN.IND_ESTADO = 'A'
                  AND DATEFROMPARTS(YEAR(A.FEC_REGISTRO), FN.MES_FERIADO, FN.DIA_FERIADO) = CAST(A.FEC_REGISTRO AS DATE)
            )
            --AND CAST(A.FEC_REGISTRO AS TIME(0)) BETWEEN '00:00:00' AND '23:00:00'
        THEN 0
        ELSE 1
    END AS IND_NO_LABORABLE,
    A.IND_ESTADO_OPERACION,
    A.FEC_REGISTRO AS FEC_HORA_INICIO,
    A.FEC_MODIFICO AS FEC_HORA_FIN,
    CAST(DATEDIFF(MILLISECOND, A.FEC_REGISTRO, A.FEC_MODIFICO) / 1000.0 AS DECIMAL(10,2)) AS VAL_SEGUNDOS
FROM CC.CC_TIN_INMEDIATA_TRANSACCION_ORDEN_TRANSFERENCIA AS A WITH (NOLOCK)
LEFT JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE TD WITH (NOLOCK) 
       ON A.NUM_TRANSFERENCIA = TD.NUM_TRANSFERENCIA
LEFT JOIN CL.CL_TIPOS_ID AS B WITH (NOLOCK) 
       ON B.COD_TIPO_ID = A.TIP_DOCUMENTO_IDENTIDAD_ORIGINANTE
LEFT JOIN CF.CF_TIN_INMEDIATA_CANAL AS C WITH (NOLOCK) 
       ON C.COD_CANAL_CCE = A.COD_CANAL
WHERE --A.IND_TRANSACCION = 'O' AND
  A.IND_ESTADO_OPERACION IN ('F','R')
  AND A.FEC_REGISTRO >= @GD_FEC_INICIO
  AND A.FEC_REGISTRO < DATEADD(DAY, 1, @GD_FEC_FIN)
  --AND CAST(A.FEC_REGISTRO AS DATE) = CAST(A.FEC_MODIFICO AS DATE)
ORDER BY A.FEC_REGISTRO ASC;
GO

DECLARE @GD_FEC_INICIO DATE = '2025-01-01';
DECLARE @GD_FEC_FIN DATE = '2025-12-31';

SELECT
    CAST(A.FEC_OPERACION_CCE AS DATE) AS FECHA_OPERACION,
    COUNT(*) AS CANTIDAD_TRANSFERENCIAS
FROM CC.CC_TIN_INMEDIATA_TRANSACCION_ORDEN_TRANSFERENCIA AS A WITH (NOLOCK)
WHERE 
    A.IND_TRANSACCION = 'O' AND A.IND_ESTADO_OPERACION = 'F' AND
	CAST(A.FEC_OPERACION_CCE AS DATE) BETWEEN @GD_FEC_INICIO AND @GD_FEC_FIN AND
	CAST(A.FEC_REGISTRO AS DATE) = CAST(A.FEC_MODIFICO AS DATE)
GROUP BY 
    CAST(A.FEC_OPERACION_CCE AS DATE)
ORDER BY 
    FECHA_OPERACION ASC;
GO
----------------------------------------------------------------------- SCRIPT PARA MI TESIS TIN DIFERIDA --------------------------------------------------------------
--EXEC CC.USP_CC_RPT_TRANSFERENCIAS_PRESENTADAS_SALIDA_CCE 'D','20250401','20250430', '%'
DECLARE @ADT_FEC_INICIO DATETIME = '20250101';
DECLARE @ADT_FEC_FIN DATETIME = '20251231';

SET @ADT_FEC_INICIO = CONVERT(DATETIME,@ADT_FEC_INICIO)          
SET @ADT_FEC_FIN = DATEADD(ms,-3, CONVERT(DATETIME,  DATEADD(DD,1,CONVERT(DATE,  @ADT_FEC_FIN))))          
                 
 DECLARE @LTBL_CABECERA_ARCHIVO TABLE              
 (  NUM_SEC_ARCHIVO INT,          
   PRIMARY KEY(NUM_SEC_ARCHIVO)          
 )             
 INSERT INTO @LTBL_CABECERA_ARCHIVO          
 SELECT CA.NUM_SEC_ARCHIVO FROM BA.BA_TIN_CABECERA_ARCHIVO CA              
  WHERE CONVERT(DATE,CA.FEC_PRESENTACION) BETWEEN @ADT_FEC_INICIO AND @ADT_FEC_FIN          
   AND CA.COD_APLICACION LIKE '%'           
   AND CA.TIPO_SESION = '1'          
   AND NOM_ARCHIVO LIKE 'EC%'        
                 
 DECLARE @LTBL_CABECERA_DETALLE TABLE              
 (  NUM_SEC_ARCHIVO INT,           
   NUM_SEC_LOTE INT,          
   NUM_SEC_REGISTRO INT,          
   SECUENCIA CHAR(7),          
   PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_SEC_LOTE, NUM_SEC_REGISTRO)          
 )             
 INSERT INTO @LTBL_CABECERA_DETALLE          
 SELECT CA.NUM_SEC_ARCHIVO, RI.NUM_SEC_LOTE, RI.NUM_SEC_REGISTRO, RI.SECUENCIA         
 FROM @LTBL_CABECERA_ARCHIVO CA            
  INNER JOIN BA.BA_TIN_REGISTRO_INDIVIDUAL RI (NOLOCK) ON CA.NUM_SEC_ARCHIVO = RI.NUM_SEC_ARCHIVO          
            
 DECLARE @LTBL_MOVIMIENTO_ARCHIVO TABLE              
 (           
   NUM_SEC_ARCHIVO INT,          
   NUM_TRANSFERENCIA INT,           
   NUM_DETALLE INT,          
   NUM_SEC_LOTE INT,          
   NUM_SEC_REGISTRO INT,             
   SECUENCIA CHAR(7) ,        
   ID_FORMA INT,         
   TIP_TRANSFERENCIA INT,        
   PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_TRANSFERENCIA, secuencia, ID_FORMA,TIP_TRANSFERENCIA)         
 )     
        
 INSERT INTO @LTBL_MOVIMIENTO_ARCHIVO        
 SELECT CA.NUM_SEC_ARCHIVO, TDC.NUM_TRANSFERENCIA, TDC.NUM_DETALLE, CA.NUM_SEC_LOTE, CA.NUM_SEC_REGISTRO, CA.SECUENCIA  , 1, ENC.TIP_TRANSFERENCIA        
 FROM @LTBL_CABECERA_DETALLE CA          
  inner JOIN  CC.CC_TRANSFERENCIAS_DETALLE_CCE TDC (NOLOCK) ON               
      CA.SECUENCIA =         
  CASE WHEN LEN(TDC.NUM_TRANSFERENCIA)<=4 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('000' +  CONVERT(VARCHAR(10),TDC.NUM_DETALLE),3)  ,7)        
 WHEN LEN(TDC.NUM_TRANSFERENCIA)=5 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('00' +  CONVERT(VARCHAR(10),TDC.NUM_DETALLE),2) ,7)        
 WHEN LEN(TDC.NUM_TRANSFERENCIA)=6 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('0' +  CONVERT(VARCHAR(10),TDC.NUM_DETALLE),1) ,7)        
  WHEN LEN(TDC.NUM_TRANSFERENCIA)>=7 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('' +  CONVERT(VARCHAR(10),TDC.NUM_DETALLE),0) ,7)         
  END        
         
  INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO ENC (NOLOCK) ON TDC.NUM_TRANSFERENCIA = ENC.NUM_TRANSFERENCIA AND ENC.TIP_TRANSFERENCIA != 'HEC' --apereira ticket 28237         
  INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA T (NOLOCK) ON T.COD_TIN_TIPO_TRANSFERENCIA=ENC.TIP_TRANSFERENCIA AND T.IND_ESTADO='A'        
       
 DECLARE @LTBL_MOVIMIENTO_ARCHIVO2 TABLE              
 (           
   NUM_SEC_ARCHIVO INT,          
   NUM_TRANSFERENCIA INT,           
   NUM_DETALLE INT,          
   NUM_SEC_LOTE INT,          
   NUM_SEC_REGISTRO INT,             
   SECUENCIA CHAR(7)  ,           
   ID_FORMA INT ,        
   TIP_TRANSFERENCIA INT,            
   PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_TRANSFERENCIA, secuencia, ID_FORMA,TIP_TRANSFERENCIA)          
 )             
     
        
INSERT INTO @LTBL_MOVIMIENTO_ARCHIVO2        
select ca.NUM_SEC_ARCHIVO, ENC.NUM_TRANSFERENCIA, DET.NUM_DETALLE, ca.NUM_SEC_LOTE, ca.NUM_SEC_REGISTRO, ca.SECUENCIA, 2 ,ENC.TIP_TRANSFERENCIA        
from @LTBL_CABECERA_DETALLE ca left outer join @LTBL_MOVIMIENTO_ARCHIVO ma        
on ca.num_sec_archivo = ma.num_sec_archivo and ca.NUM_SEC_LOTE = ma.NUM_SEC_LOTE and ca.NUM_SEC_ARCHIVO = ma.NUM_SEC_ARCHIVO  and ca.secuencia = ma.secuencia         
INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE DET (NOLOCK) ON DET.ID_DETALLE = CA.SECUENCIA        
INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO ENC (NOLOCK) ON  ENC.NUM_TRANSFERENCIA = DET.NUM_TRANSFERENCIA AND ENC.TIP_TRANSFERENCIA != 'HEC'    
INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA T (NOLOCK) ON T.COD_TIN_TIPO_TRANSFERENCIA=ENC.TIP_TRANSFERENCIA AND T.IND_ESTADO='A'        
where ma.SECUENCIA is null        
        
DECLARE @LTBL_MOVIMIENTO_ARCHIVO3 TABLE              
 (           
   NUM_SEC_ARCHIVO INT,          
   NUM_TRANSFERENCIA INT,           
   NUM_DETALLE INT,          
   NUM_SEC_LOTE INT,          
   NUM_SEC_REGISTRO INT,             
   SECUENCIA CHAR(7)    ,        
      ID_FORMA INT,        
   TIP_TRANSFERENCIA INT,             
   PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_TRANSFERENCIA, secuencia, ID_FORMA,TIP_TRANSFERENCIA)          
 )           
        
INSERT INTO @LTBL_MOVIMIENTO_ARCHIVO3        
select * from @LTBL_MOVIMIENTO_ARCHIVO        
union all        
select * from @LTBL_MOVIMIENTO_ARCHIVO2       
              
 DECLARE @LTBL_MOVIMIENTO TABLE              
 (  NUM_TRANSFERENCIA INT,          
   NUM_MOVIMIENTO DECIMAL (10,0),          
   COD_AGENCIA VARCHAR(5),             
   TIP_TRANSACCION VARCHAR(5),          
   SUB_TIP_TRANSACCION VARCHAR(5),          
   COD_PRODUCTO VARCHAR(5),          
   NUM_ASIENTO DECIMAL (10,0),            
   FEC_TRANSACCION DATETIME,           
   MON_ITF DECIMAL (18,2),        
   TIP_TRANSFERENCIA VARCHAR(3),    
    NUM_ID INT            
   PRIMARY KEY(NUM_TRANSFERENCIA,NUM_ID)         
 )
         
 INSERT INTO @LTBL_MOVIMIENTO          
 SELECT TE.NUM_TRANSFERENCIA, M.NUM_MOVIMIENTO, M.COD_AGENCIA, M.TIP_TRANSACCION, M.SUBTIP_TRANSAC, M.COD_PRODUCTO,          
  M.NUM_ASIENTO, M.FEC_MOVIMIENTO, MON_ITF = ISNULL(M2.MON_MOVIMIENTO,0), TT.COD_TIN_TIPO_TRANSFERENCIA,    
  DE.ID_DETALLE              
  FROM CC.CC_MOVIMTO_DIARIO M (NOLOCK)          
   INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO TE (NOLOCK) ON M.NUM_MOVIMIENTO = TE.NUM_MOVIMIENTO          
   INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE DE (NOLOCK) ON TE.NUM_TRANSFERENCIA = DE.NUM_TRANSFERENCIA            
    INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA TT  (NOLOCK) ON TE.TIP_TRANSFERENCIA = TT.COD_TIN_TIPO_TRANSFERENCIA          
   LEFT JOIN CC.CC_MOVIMTO_DIARIO M2 (NOLOCK) ON M.NUM_MOVIMIENTO = M2.NUM_MOV_FUENTE AND M2.EST_MOVIMIENTO = 'A' AND M2.TIP_TRANSACCION = '203'          
   INNER JOIN (SELECT DISTINCT NUM_TRANSFERENCIA, TIP_TRANSFERENCIA FROM @LTBL_MOVIMIENTO_ARCHIVO3) TD ON TD.NUM_TRANSFERENCIA = TE.NUM_TRANSFERENCIA AND TD.TIP_TRANSFERENCIA = TE.TIP_TRANSFERENCIA        
  WHERE          
  M.EST_MOVIMIENTO <> 'N' AND TE.IND_ESTADO <> 'N'          
 UNION ALL          
 SELECT TE.NUM_TRANSFERENCIA, M.NUM_MOVIMIENTO, M.COD_AGENCIA, M.TIP_TRANSACCION, M.SUBTIP_TRANSAC, M.COD_PRODUCTO,          
  M.NUM_ASIENTO, M.FEC_MOVIMIENTO, MON_ITF = ISNULL(M2.MON_MOVIMIENTO,0), TT.COD_TIN_TIPO_TRANSFERENCIA,    
  DE.ID_DETALLE              
  FROM CC.CC_MOVIMTO_MENSUAL M (NOLOCK)          
   INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO TE (NOLOCK) ON M.NUM_MOVIMIENTO = TE.NUM_MOVIMIENTO          
      INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE DE (NOLOCK) ON TE.NUM_TRANSFERENCIA = DE.NUM_TRANSFERENCIA         
    INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA TT  (NOLOCK) ON TE.TIP_TRANSFERENCIA = TT.COD_TIN_TIPO_TRANSFERENCIA          
   LEFT JOIN CC.CC_MOVIMTO_MENSUAL M2 (NOLOCK) ON M.NUM_MOVIMIENTO = M2.NUM_MOV_FUENTE AND M2.EST_MOVIMIENTO = 'A' AND M2.TIP_TRANSACCION = '203'          
      INNER JOIN (SELECT DISTINCT NUM_TRANSFERENCIA, TIP_TRANSFERENCIA FROM @LTBL_MOVIMIENTO_ARCHIVO3) TD ON TD.NUM_TRANSFERENCIA = TE.NUM_TRANSFERENCIA AND TD.TIP_TRANSFERENCIA= TE.TIP_TRANSFERENCIA        
WHERE M.EST_MOVIMIENTO <> 'N' AND TE.IND_ESTADO <> 'N'           
                 
 DECLARE @LTBL_MOVIMIENTO_FINAL TABLE              
 (  NUM_TRANSFERENCIA INT,          
   NUM_MOVIMIENTO DECIMAL (10,0),          
   COD_AGENCIA VARCHAR(5),             
   TIP_TRANSACCION VARCHAR(5),          
   SUB_TIP_TRANSACCION VARCHAR(5),          
   COD_PRODUCTO VARCHAR(5),          
   NUM_ASIENTO DECIMAL (10,0),            
   FEC_TRANSACCION DATETIME,           
   MON_ITF DECIMAL (18,2),         
   TIP_TRANSFERENCIA VARCHAR(3),     
   NUM_ID INT                  
   PRIMARY KEY(NUM_TRANSFERENCIA,NUM_ID)        
 )          
        
INSERT INTO @LTBL_MOVIMIENTO_FINAL        
SELECT * FROM @LTBL_MOVIMIENTO WHERE         
FEC_TRANSACCION >=  DATEADD(MONTH, -1, @ADT_FEC_INICIO);
  
WITH TBL_REGISTROS AS (
	SELECT
		NUM_SEC_RESPUESTA,
		NUM_SEC_ARCHIVO,
		DET_REGISTRO,
		Tipo = 
			CASE 
				WHEN DET_REGISTRO LIKE '%FECHA%' THEN 'FECHA'
				WHEN DET_REGISTRO LIKE '%HORA%' THEN 'HORA'
				ELSE NULL
			END,
		ROW_NUMBER() OVER (PARTITION BY NUM_SEC_ARCHIVO ORDER BY NUM_SEC_RESPUESTA) AS RN
	FROM BA.BA_TIN_DETALLE_ARCHIVO_RESPUESTA
	WHERE DET_REGISTRO LIKE '%FECHA%' OR DET_REGISTRO LIKE '%HORA%'
),
TBL_FECHAS AS (
	SELECT * FROM TBL_REGISTROS WHERE Tipo = 'FECHA'
),
TBL_HORAS AS (
	SELECT * FROM TBL_REGISTROS WHERE Tipo = 'HORA'
),
TBL_ARCHIVO AS (
	SELECT
		f.NUM_SEC_ARCHIVO,
		FECHA_HORA = CONVERT(DATETIME,
			LTRIM(RTRIM(SUBSTRING(f.DET_REGISTRO, CHARINDEX('FECHA', f.DET_REGISTRO) + 9, 11))) + ' ' +
			LTRIM(RTRIM(SUBSTRING(h.DET_REGISTRO, CHARINDEX('HORA', h.DET_REGISTRO) + 12, 8)))
		, 103)
	FROM TBL_FECHAS f
	JOIN TBL_HORAS h
		ON f.NUM_SEC_ARCHIVO = h.NUM_SEC_ARCHIVO
		AND h.RN = f.RN + 1
)
SELECT 
	CA.NUM_SEC_ARCHIVO AS ID_TRANSACCION,
	'SALIENTE' AS IND_TRANSACCION,
	TE.NUM_TRANSFERENCIA,
	CASE WHEN TE.TIP_TRANSFERENCIA = '220' THEN 'TRANSFERENCIA ORDINARIA' 
        ELSE 'PAGO TARJETA DE CREDITO' 
    END AS TIP_TRANSFERENCIA,
	TI.DES_TIPO_ID AS TIP_DOC_ORIGINANTE,
	TDC.NUM_DOCUMENTO AS NUM_IDENTIDAD_ORIGINANTE,
	CL.NOM_CLIENTE AS NOM_ORIGINANTE,
	'' AS DES_CANAL,
	CASE WHEN TE.COD_MONEDA = '1' THEN 'SOLES' ELSE 'DOLARES' END AS DES_MONEDA,
	TE.MON_TRANSFERENCIA,
	TDC.MON_COMISION AS MON_COMISION_CMACT,
	CAST(TRY_CAST(RI.IMPORTE_COMISION AS BIGINT) / 100.0 AS DECIMAL(18,2)) AS MON_COMISION_CCE,
	MON_COMISION_TOTAL = ISNULL(TDC.MON_COMISION,0) - ISNULL(CAST(TRY_CAST(RI.IMPORTE_COMISION AS BIGINT) / 100.0 AS DECIMAL(18,2)),0),
	    CASE
        WHEN 
            DATEPART(WEEKDAY, CAST(MOV.FEC_TRANSACCION AS DATE)) NOT IN (6, 7)
            AND NOT EXISTS (
                SELECT 1
                FROM CF.CF_TIN_DIA_NO_LABORABLE DNL WITH (NOLOCK)
                WHERE DNL.IND_ESTADO = 'A'
                  AND DNL.FEC_NO_LABORABLE = CAST(MOV.FEC_TRANSACCION AS DATE)
            )
            AND NOT EXISTS (
                SELECT 1
                FROM CF.CF_FERIADO_NACIONAL FN WITH (NOLOCK)
                WHERE FN.IND_ESTADO = 'A'
                  AND DATEFROMPARTS(YEAR(MOV.FEC_TRANSACCION), FN.MES_FERIADO, FN.DIA_FERIADO) = CAST(MOV.FEC_TRANSACCION AS DATE)
            )
            --AND CAST(MOV.FEC_TRANSACCION AS TIME(0)) BETWEEN '06:00:00' AND '18:30:00'
        THEN 0
        ELSE 1
    END AS IND_NO_LABORABLE,
	IND_ESTADO_OPERACION = CASE CA.IND_ESTADO WHEN 'G' THEN 'GENERADO' WHEN 'R' THEN 'F' WHEN 'E' THEN 'R' WHEN 'N' THEN 'ANULADO' END,
	FEC_HORA_INICIO = MOV.FEC_TRANSACCION,           
	TBL.FECHA_HORA AS FEC_HORA_FIN,
	CAST(DATEDIFF(MILLISECOND, MOV.FEC_TRANSACCION, TBL.FECHA_HORA) / 1000.0 AS DECIMAL(10,2)) AS VAL_SEGUNDOS
 FROM CC.CC_TRANSFERENCIAS_ENCABEZADO TE (NOLOCK)          
 INNER JOIN @LTBL_MOVIMIENTO_FINAL MOV
  ON TE.NUM_MOVIMIENTO = MOV.NUM_MOVIMIENTO          
 INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE TDC (NOLOCK)           
  ON TE.NUM_TRANSFERENCIA = TDC.NUM_TRANSFERENCIA AND TE.TIP_TRANSFERENCIA != 'HEC'        
  INNER JOIN @LTBL_MOVIMIENTO_ARCHIVO3 MOVD          
   ON TDC.NUM_TRANSFERENCIA = MOVD.NUM_TRANSFERENCIA AND TDC.NUM_DETALLE = MOVD.NUM_DETALLE
   AND TE.TIP_TRANSFERENCIA = MOVD.TIP_TRANSFERENCIA        
   INNER JOIN BA.BA_TIN_REGISTRO_INDIVIDUAL RI (NOLOCK)           
    ON MOVD.NUM_SEC_ARCHIVO = RI.NUM_SEC_ARCHIVO AND RI.NUM_SEC_REGISTRO = MOVD.NUM_SEC_REGISTRO          
     AND MOVD.NUM_SEC_LOTE = RI.NUM_SEC_LOTE AND MOVD.NUM_SEC_REGISTRO = RI.NUM_SEC_REGISTRO         
  AND ((RI.NUM_CUENTA_ACREDITAR = (CASE WHEN TE.TIP_TRANSFERENCIA = 220 THEN TDC.NUM_CUENTA_CCI END )) OR         
  (RI.NUM_CUENTA_ACREDITAR != (CASE WHEN TE.TIP_TRANSFERENCIA != 220 THEN TDC.NUM_CUENTA_CCI END ) ))         
     INNER JOIN BA.BA_TIN_CABECERA_ARCHIVO CA (NOLOCK)          
      ON RI.NUM_SEC_ARCHIVO = CA.NUM_SEC_ARCHIVO          
     INNER JOIN BA.BA_TIN_CABECERA_LOTE BL (NOLOCK)           
      ON RI.NUM_SEC_ARCHIVO = BL.NUM_SEC_ARCHIVO AND RI.NUM_SEC_LOTE = BL.NUM_SEC_LOTE           
     INNER JOIN BA.BA_TIN_REGISTRO_ADICIONAL RA (NOLOCK)           
      ON RI.NUM_SEC_ARCHIVO = RA.NUM_SEC_ARCHIVO AND RI.NUM_SEC_LOTE = RA.NUM_SEC_LOTE           
       AND RI.NUM_SEC_REGISTRO = RA.NUM_SEC_REGISTRO        
 INNER JOIN CL.CL_CLIENTES CL (NOLOCK)          
  ON TE.COD_CLIENTE = CL.COD_CLIENTE          
 INNER JOIN CC.CC_CUENTA_EFECTIVO CE (NOLOCK)          
  ON TE.NUM_CUENTA = CE.NUM_CUENTA         
  AND CE.COD_EMPRESA = '1'        
  INNER JOIN CF.CF_MONEDAS MO (NOLOCK)          
   ON CE.COD_MONEDA = MO.COD_MONEDA          
  INNER JOIN CF.CF_AGENCIAS AG1 (NOLOCK)          
   ON CE.COD_AGENCIA = AG1.COD_AGENCIA          
   AND AG1.COD_EMPRESA = '1'        
 INNER JOIN BA.BA_ENTIDAD_FINANCIERA_CCE EF (NOLOCK)          
  ON EF.ID_ENTIDAD = TDC.ID_ENTIDAD        
 INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA TT  (NOLOCK)           
  ON TE.TIP_TRANSFERENCIA = TT.COD_TIN_TIPO_TRANSFERENCIA
 LEFT JOIN CL.CL_TIPOS_ID TI (NOLOCK)          
  ON TDC.COD_TIPO_DOCUMENTO = TI.COD_TIPO_ID_CCE          
  AND TI.COD_EMPRESA = '1'
 INNER JOIN CF.CF_AGENCIAS AG2 (NOLOCK)
  ON TE.COD_AGENCIA = AG2.COD_AGENCIA
 INNER JOIN CG.CG_ASTO_RESUMEN AR (NOLOCK)
  ON MOV.NUM_ASIENTO = AR.NUM_ASIENTO
  INNER JOIN CG.CG_ESTADOS_ASIENTO EAC (NOLOCK)          
   ON AR.EST_ASIENTO = EAC.COD_ESTADO
 INNER JOIN TBL_ARCHIVO AS TBL ON TBL.NUM_SEC_ARCHIVO = CA.NUM_SEC_ARCHIVO 
 WHERE TE.IND_ESTADO IN ('E') 
 --AND CAST(MOV.FEC_TRANSACCION AS DATE) = CAST(TBL.FECHA_HORA AS DATE)
ORDER BY FEC_HORA_INICIO, CA.IND_ESTADO  ASC
GO

/**************************************************************************
CANTIDAD DE TRANSACCIONES POR DIA
*******************************************************************/
DECLARE @ADT_FEC_INICIO DATETIME = '20250101';
DECLARE @ADT_FEC_FIN DATETIME = '20251231';

SET @ADT_FEC_INICIO = CONVERT(DATETIME,@ADT_FEC_INICIO);
SET @ADT_FEC_FIN = DATEADD(ms,-3, CONVERT(DATETIME,  DATEADD(DD,1,CONVERT(DATE,  @ADT_FEC_FIN))));

DECLARE @LTBL_CABECERA_ARCHIVO TABLE
(
  NUM_SEC_ARCHIVO INT,
  PRIMARY KEY(NUM_SEC_ARCHIVO)
);
INSERT INTO @LTBL_CABECERA_ARCHIVO
SELECT CA.NUM_SEC_ARCHIVO
FROM BA.BA_TIN_CABECERA_ARCHIVO CA
WHERE CONVERT(DATE,CA.FEC_PRESENTACION) BETWEEN @ADT_FEC_INICIO AND @ADT_FEC_FIN
  AND CA.COD_APLICACION LIKE '%'
  AND CA.TIPO_SESION = '1'
  AND NOM_ARCHIVO LIKE 'EC%';

DECLARE @LTBL_CABECERA_DETALLE TABLE
(
  NUM_SEC_ARCHIVO INT,
  NUM_SEC_LOTE INT,
  NUM_SEC_REGISTRO INT,
  SECUENCIA CHAR(7),
  PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_SEC_LOTE, NUM_SEC_REGISTRO)
);
INSERT INTO @LTBL_CABECERA_DETALLE
SELECT CA.NUM_SEC_ARCHIVO, RI.NUM_SEC_LOTE, RI.NUM_SEC_REGISTRO, RI.SECUENCIA
FROM @LTBL_CABECERA_ARCHIVO CA
INNER JOIN BA.BA_TIN_REGISTRO_INDIVIDUAL RI (NOLOCK)
  ON CA.NUM_SEC_ARCHIVO = RI.NUM_SEC_ARCHIVO;

DECLARE @LTBL_MOVIMIENTO_ARCHIVO TABLE
(
  NUM_SEC_ARCHIVO INT,
  NUM_TRANSFERENCIA INT,
  NUM_DETALLE INT,
  NUM_SEC_LOTE INT,
  NUM_SEC_REGISTRO INT,
  SECUENCIA CHAR(7),
  ID_FORMA INT,
  TIP_TRANSFERENCIA INT,
  PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_TRANSFERENCIA, secuencia, ID_FORMA, TIP_TRANSFERENCIA)
);

INSERT INTO @LTBL_MOVIMIENTO_ARCHIVO
SELECT
  CA.NUM_SEC_ARCHIVO,
  TDC.NUM_TRANSFERENCIA,
  TDC.NUM_DETALLE,
  CA.NUM_SEC_LOTE,
  CA.NUM_SEC_REGISTRO,
  CA.SECUENCIA,
  1,
  ENC.TIP_TRANSFERENCIA
FROM @LTBL_CABECERA_DETALLE CA
INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE TDC (NOLOCK)
  ON CA.SECUENCIA =
     CASE
       WHEN LEN(TDC.NUM_TRANSFERENCIA) <= 4 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('000' + CONVERT(VARCHAR(10),TDC.NUM_DETALLE),3),7)
       WHEN LEN(TDC.NUM_TRANSFERENCIA) = 5 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('00' + CONVERT(VARCHAR(10),TDC.NUM_DETALLE),2),7)
       WHEN LEN(TDC.NUM_TRANSFERENCIA) = 6 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('0' + CONVERT(VARCHAR(10),TDC.NUM_DETALLE),1),7)
       WHEN LEN(TDC.NUM_TRANSFERENCIA) >= 7 THEN RIGHT('0000000' + CONVERT(VARCHAR(10),TDC.NUM_TRANSFERENCIA) + RIGHT('' + CONVERT(VARCHAR(10),TDC.NUM_DETALLE),0),7)
     END
INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO ENC (NOLOCK)
  ON TDC.NUM_TRANSFERENCIA = ENC.NUM_TRANSFERENCIA
 AND ENC.TIP_TRANSFERENCIA != 'HEC'
INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA T (NOLOCK)
  ON T.COD_TIN_TIPO_TRANSFERENCIA = ENC.TIP_TRANSFERENCIA
 AND T.IND_ESTADO = 'A';

DECLARE @LTBL_MOVIMIENTO_ARCHIVO2 TABLE
(
  NUM_SEC_ARCHIVO INT,
  NUM_TRANSFERENCIA INT,
  NUM_DETALLE INT,
  NUM_SEC_LOTE INT,
  NUM_SEC_REGISTRO INT,
  SECUENCIA CHAR(7),
  ID_FORMA INT,
  TIP_TRANSFERENCIA INT,
  PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_TRANSFERENCIA, secuencia, ID_FORMA, TIP_TRANSFERENCIA)
);

INSERT INTO @LTBL_MOVIMIENTO_ARCHIVO2
SELECT
  ca.NUM_SEC_ARCHIVO,
  ENC.NUM_TRANSFERENCIA,
  DET.NUM_DETALLE,
  ca.NUM_SEC_LOTE,
  ca.NUM_SEC_REGISTRO,
  ca.SECUENCIA,
  2,
  ENC.TIP_TRANSFERENCIA
FROM @LTBL_CABECERA_DETALLE ca
LEFT OUTER JOIN @LTBL_MOVIMIENTO_ARCHIVO ma
  ON ca.num_sec_archivo = ma.num_sec_archivo
 AND ca.NUM_SEC_LOTE = ma.NUM_SEC_LOTE
 AND ca.NUM_SEC_ARCHIVO = ma.NUM_SEC_ARCHIVO
 AND ca.secuencia = ma.secuencia
INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE DET (NOLOCK)
  ON DET.ID_DETALLE = CA.SECUENCIA
INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO ENC (NOLOCK)
  ON ENC.NUM_TRANSFERENCIA = DET.NUM_TRANSFERENCIA
 AND ENC.TIP_TRANSFERENCIA != 'HEC'
INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA T (NOLOCK)
  ON T.COD_TIN_TIPO_TRANSFERENCIA = ENC.TIP_TRANSFERENCIA
 AND T.IND_ESTADO = 'A'
WHERE ma.SECUENCIA IS NULL;

DECLARE @LTBL_MOVIMIENTO_ARCHIVO3 TABLE
(
  NUM_SEC_ARCHIVO INT,
  NUM_TRANSFERENCIA INT,
  NUM_DETALLE INT,
  NUM_SEC_LOTE INT,
  NUM_SEC_REGISTRO INT,
  SECUENCIA CHAR(7),
  ID_FORMA INT,
  TIP_TRANSFERENCIA INT,
  PRIMARY KEY(NUM_SEC_ARCHIVO, NUM_TRANSFERENCIA, secuencia, ID_FORMA, TIP_TRANSFERENCIA)
);

INSERT INTO @LTBL_MOVIMIENTO_ARCHIVO3
SELECT * FROM @LTBL_MOVIMIENTO_ARCHIVO
UNION ALL
SELECT * FROM @LTBL_MOVIMIENTO_ARCHIVO2;

DECLARE @LTBL_MOVIMIENTO TABLE
(
  NUM_TRANSFERENCIA INT,
  NUM_MOVIMIENTO DECIMAL(10,0),
  COD_AGENCIA VARCHAR(5),
  TIP_TRANSACCION VARCHAR(5),
  SUB_TIP_TRANSACCION VARCHAR(5),
  COD_PRODUCTO VARCHAR(5),
  NUM_ASIENTO DECIMAL(10,0),
  FEC_TRANSACCION DATETIME,
  MON_ITF DECIMAL(18,2),
  TIP_TRANSFERENCIA VARCHAR(3),
  NUM_ID INT,
  PRIMARY KEY(NUM_TRANSFERENCIA,NUM_ID)
);

INSERT INTO @LTBL_MOVIMIENTO
SELECT
  TE.NUM_TRANSFERENCIA, M.NUM_MOVIMIENTO, M.COD_AGENCIA, M.TIP_TRANSACCION, M.SUBTIP_TRANSAC, M.COD_PRODUCTO,
  M.NUM_ASIENTO, M.FEC_MOVIMIENTO, MON_ITF = ISNULL(M2.MON_MOVIMIENTO,0), TT.COD_TIN_TIPO_TRANSFERENCIA,
  DE.ID_DETALLE
FROM CC.CC_MOVIMTO_DIARIO M (NOLOCK)
INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO TE (NOLOCK)
  ON M.NUM_MOVIMIENTO = TE.NUM_MOVIMIENTO
INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE DE (NOLOCK)
  ON TE.NUM_TRANSFERENCIA = DE.NUM_TRANSFERENCIA
INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA TT (NOLOCK)
  ON TE.TIP_TRANSFERENCIA = TT.COD_TIN_TIPO_TRANSFERENCIA
LEFT JOIN CC.CC_MOVIMTO_DIARIO M2 (NOLOCK)
  ON M.NUM_MOVIMIENTO = M2.NUM_MOV_FUENTE
 AND M2.EST_MOVIMIENTO = 'A'
 AND M2.TIP_TRANSACCION = '203'
INNER JOIN (SELECT DISTINCT NUM_TRANSFERENCIA, TIP_TRANSFERENCIA FROM @LTBL_MOVIMIENTO_ARCHIVO3) TD
  ON TD.NUM_TRANSFERENCIA = TE.NUM_TRANSFERENCIA
 AND TD.TIP_TRANSFERENCIA = TE.TIP_TRANSFERENCIA
WHERE M.EST_MOVIMIENTO <> 'N' AND TE.IND_ESTADO <> 'N'
UNION ALL
SELECT
  TE.NUM_TRANSFERENCIA, M.NUM_MOVIMIENTO, M.COD_AGENCIA, M.TIP_TRANSACCION, M.SUBTIP_TRANSAC, M.COD_PRODUCTO,
  M.NUM_ASIENTO, M.FEC_MOVIMIENTO, MON_ITF = ISNULL(M2.MON_MOVIMIENTO,0), TT.COD_TIN_TIPO_TRANSFERENCIA,
  DE.ID_DETALLE
FROM CC.CC_MOVIMTO_MENSUAL M (NOLOCK)
INNER JOIN CC.CC_TRANSFERENCIAS_ENCABEZADO TE (NOLOCK)
  ON M.NUM_MOVIMIENTO = TE.NUM_MOVIMIENTO
INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE DE (NOLOCK)
  ON TE.NUM_TRANSFERENCIA = DE.NUM_TRANSFERENCIA
INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA TT (NOLOCK)
  ON TE.TIP_TRANSFERENCIA = TT.COD_TIN_TIPO_TRANSFERENCIA
LEFT JOIN CC.CC_MOVIMTO_MENSUAL M2 (NOLOCK)
  ON M.NUM_MOVIMIENTO = M2.NUM_MOV_FUENTE
 AND M2.EST_MOVIMIENTO = 'A'
 AND M2.TIP_TRANSACCION = '203'
INNER JOIN (SELECT DISTINCT NUM_TRANSFERENCIA, TIP_TRANSFERENCIA FROM @LTBL_MOVIMIENTO_ARCHIVO3) TD
  ON TD.NUM_TRANSFERENCIA = TE.NUM_TRANSFERENCIA
 AND TD.TIP_TRANSFERENCIA = TE.TIP_TRANSFERENCIA
WHERE M.EST_MOVIMIENTO <> 'N' AND TE.IND_ESTADO <> 'N';

DECLARE @LTBL_MOVIMIENTO_FINAL TABLE
(
  NUM_TRANSFERENCIA INT,
  NUM_MOVIMIENTO DECIMAL(10,0),
  COD_AGENCIA VARCHAR(5),
  TIP_TRANSACCION VARCHAR(5),
  SUB_TIP_TRANSACCION VARCHAR(5),
  COD_PRODUCTO VARCHAR(5),
  NUM_ASIENTO DECIMAL(10,0),
  FEC_TRANSACCION DATETIME,
  MON_ITF DECIMAL(18,2),
  TIP_TRANSFERENCIA VARCHAR(3),
  NUM_ID INT,
  PRIMARY KEY(NUM_TRANSFERENCIA,NUM_ID)
);

INSERT INTO @LTBL_MOVIMIENTO_FINAL
SELECT * FROM @LTBL_MOVIMIENTO
WHERE FEC_TRANSACCION >= DATEADD(MONTH, -1, @ADT_FEC_INICIO);

;WITH TBL_REGISTROS AS
(
  SELECT
    NUM_SEC_RESPUESTA,
    NUM_SEC_ARCHIVO,
    DET_REGISTRO,
    Tipo =
      CASE
        WHEN DET_REGISTRO LIKE '%FECHA%' THEN 'FECHA'
        WHEN DET_REGISTRO LIKE '%HORA%' THEN 'HORA'
        ELSE NULL
      END,
    ROW_NUMBER() OVER (PARTITION BY NUM_SEC_ARCHIVO ORDER BY NUM_SEC_RESPUESTA) AS RN
  FROM BA.BA_TIN_DETALLE_ARCHIVO_RESPUESTA
  WHERE DET_REGISTRO LIKE '%FECHA%' OR DET_REGISTRO LIKE '%HORA%'
),
TBL_FECHAS AS
(
  SELECT * FROM TBL_REGISTROS WHERE Tipo = 'FECHA'
),
TBL_HORAS AS
(
  SELECT * FROM TBL_REGISTROS WHERE Tipo = 'HORA'
),
TBL_ARCHIVO AS
(
  SELECT
    f.NUM_SEC_ARCHIVO,
    FECHA_HORA = CONVERT(DATETIME,
      LTRIM(RTRIM(SUBSTRING(f.DET_REGISTRO, CHARINDEX('FECHA', f.DET_REGISTRO) + 9, 11))) + ' ' +
      LTRIM(RTRIM(SUBSTRING(h.DET_REGISTRO, CHARINDEX('HORA', h.DET_REGISTRO) + 12, 8)))
    , 103)
  FROM TBL_FECHAS f
  JOIN TBL_HORAS h
    ON f.NUM_SEC_ARCHIVO = h.NUM_SEC_ARCHIVO
   AND h.RN = f.RN + 1
)
-- === CANTIDAD DE TRANSFERENCIAS POR DÍA (DIFERIDAS) ===
SELECT
  CAST(MOV.FEC_TRANSACCION AS DATE) AS FECHA_OPERACION,
  COUNT(*) AS CANTIDAD_TRANSFERENCIAS
FROM CC.CC_TRANSFERENCIAS_ENCABEZADO TE (NOLOCK)
INNER JOIN @LTBL_MOVIMIENTO_FINAL MOV
  ON TE.NUM_MOVIMIENTO = MOV.NUM_MOVIMIENTO
INNER JOIN CC.CC_TRANSFERENCIAS_DETALLE_CCE TDC (NOLOCK)
  ON TE.NUM_TRANSFERENCIA = TDC.NUM_TRANSFERENCIA
 AND TE.TIP_TRANSFERENCIA != 'HEC'
INNER JOIN @LTBL_MOVIMIENTO_ARCHIVO3 MOVD
  ON TDC.NUM_TRANSFERENCIA = MOVD.NUM_TRANSFERENCIA
 AND TDC.NUM_DETALLE = MOVD.NUM_DETALLE
 AND TE.TIP_TRANSFERENCIA = MOVD.TIP_TRANSFERENCIA
INNER JOIN BA.BA_TIN_REGISTRO_INDIVIDUAL RI (NOLOCK)
  ON MOVD.NUM_SEC_ARCHIVO = RI.NUM_SEC_ARCHIVO
 AND RI.NUM_SEC_REGISTRO = MOVD.NUM_SEC_REGISTRO
 AND MOVD.NUM_SEC_LOTE = RI.NUM_SEC_LOTE
 AND MOVD.NUM_SEC_REGISTRO = RI.NUM_SEC_REGISTRO
INNER JOIN BA.BA_TIN_CABECERA_ARCHIVO CA (NOLOCK)
  ON RI.NUM_SEC_ARCHIVO = CA.NUM_SEC_ARCHIVO
INNER JOIN BA.BA_TIN_CABECERA_LOTE BL (NOLOCK)
  ON RI.NUM_SEC_ARCHIVO = BL.NUM_SEC_ARCHIVO
 AND RI.NUM_SEC_LOTE = BL.NUM_SEC_LOTE
INNER JOIN BA.BA_TIN_REGISTRO_ADICIONAL RA (NOLOCK)
  ON RI.NUM_SEC_ARCHIVO = RA.NUM_SEC_ARCHIVO
 AND RI.NUM_SEC_LOTE = RA.NUM_SEC_LOTE
 AND RI.NUM_SEC_REGISTRO = RA.NUM_SEC_REGISTRO
INNER JOIN CF.CF_TIN_TIPO_TRANSFERENCIA TT  (NOLOCK)
  ON TE.TIP_TRANSFERENCIA = TT.COD_TIN_TIPO_TRANSFERENCIA
INNER JOIN TBL_ARCHIVO AS TBL
  ON TBL.NUM_SEC_ARCHIVO = CA.NUM_SEC_ARCHIVO
WHERE
  TE.IND_ESTADO IN ('E')
  AND CAST(MOV.FEC_TRANSACCION AS DATE) = CAST(TBL.FECHA_HORA AS DATE)
GROUP BY
  CAST(MOV.FEC_TRANSACCION AS DATE)
ORDER BY
  FECHA_OPERACION ASC;
GO
