# must be unique in a given SonarQube instance
sonar.projectKey=sqp_871f0367a728889dd3c07e722c175e980da7f183

# --- optional properties ---
# defaults to project key
sonar.projectName=TakanaApiTransferenciasCCE
# defaults to 'not provided'
sonar.projectVersion=1.0
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.login=admin
sonae.passwors=sonar


# Path is relative to the sonar-project.properties file. Defaults to .
#sonar.sources=.

#############################################
sonar.issuesReport.html.enable=true
sonar.report.export.path=sonar-report.json
sonar.sources=.
sonar.java.binaries=./binaries

#sonar.analysis.mode=preview
sonar.issuesReport.html.enable=true
sonar.report.export.path=report.json

# Change the host.url to point to the
# sonarqube server (default localhost)
sonar.host.url=http://192.168.112.17:9010/